name: .NET Core

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies of Library
      run: dotnet restore ./src/GCodeViewer.Library/GCodeViewer.Library.csproj
    - name: Install dependencies of Testing Project
      run: dotnet restore ./src/GCodeViewer.Library.Tests/GCodeViewer.Library.Tests.csproj
    - name: Build Library
      run: dotnet build --configuration Release --no-restore ./src/GCodeViewer.Library/GCodeViewer.Library.csproj
    - name: Build Test Project
      run: dotnet build --configuration Release --no-restore ./src/GCodeViewer.Library.Tests/GCodeViewer.Library.Tests.csproj
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal ./src
